# Generated by Django 3.2.4 on 2021-06-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='projects/')),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('BG', 'BLOG'), ('EN', 'ENTERTAINMENT'), ('EC', 'ECOMMERCE'), ('TC', 'TECH'), ('O', 'OTHER')], max_length=2)),
                ('link', models.URLField(verbose_name='link_to_project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
