# Generated by Django 3.1.7 on 2021-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210315_1948'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to='portfolio.UserProfile'),
        ),
    ]
