# Generated by Django 3.2.4 on 2021-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210611_0140'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(related_name='project_user', to='portfolio.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='portfolio.UserProfile'),
        ),
    ]
