# Generated by Django 3.2.4 on 2021-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('projects', '0002_auto_20210611_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(related_name='tools', to='tags.Tag'),
        ),
    ]
