# Generated by Django 3.1.7 on 2021-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210320_1428'),
        ('projects', '0004_auto_20210317_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='portfolio.UserProfile'),
        ),
    ]
