# Generated by Django 3.1.7 on 2021-03-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210321_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author',
        ),
    ]
