# Generated by Django 3.2.4 on 2021-06-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210611_0140'),
        ('team', '0002_ourteam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.userprofile'),
        ),
    ]
