# Generated by Django 3.1.7 on 2021-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='user_<built-in function id>/')),
                ('github', models.URLField(blank=True, null=True, verbose_name='github_link')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin_link')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
