# Generated by Django 3.1.7 on 2021-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210322_2139'),
        ('portfolio', '0006_auto_20210323_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Project'),
        ),
    ]
